### ISSUE TITLE
TypeError: player.touchOverlay is not a function

### ISSUE THREAD

**Issue by oinsua** [hoangvu12/videojs-overlay-buttons#1]
I am testing the lib and I get this error when I use the following example.

var videojs = require("video.js");

// The actual plugin function is exported by this module, but it is also
// attached to the `Player.prototype`; so, there is no need to assign it
// to a variable.
require("videojs-overlay-buttons");

var player = videojs("my-video");

player.touchOverlay(options);

**Comment by hoangvu12** [comment]
Can you show me how you import videojs and videojs-overlay-button?

If you import them through a cdn, then there is example about it in README.md

**Comment by briquetech** [comment]
I am trying to use this in an IONIC application.
````
var self = this;
this.player = videojs(this.target.nativeElement, this.options, function onPlayerReady() { });
this.player.touchOverlay({
				seekLeft: {
					handleClick: () => {
						const time = Number(self.player.currentTime()) - 10;
						self.player.currentTime(time);
					},
					doubleTap: true,
				},
				play: {
					handleClick: () => {
						if (self.player.paused()) {
							self.player.play();
						} else {
							self.player.pause();
						}
					},
				},
				seekRight: {
					handleClick: () => {
						const time = Number(self.player.currentTime()) + 10;
						self.player.currentTime(time);
					},
					doubleTap: true,
				},
				lockButton: true
			});
````
Somehow it is saying this method is not defined.

**Comment by hoangvu12** [comment]
> I am trying to use this in an IONIC application.
> ````
> var self = this;
> this.player = videojs(this.target.nativeElement, this.options, function onPlayerReady() { });
> this.player.touchOverlay({
> 				seekLeft: {
> 					handleClick: () => {
> 						const time = Number(self.player.currentTime()) - 10;
> 						self.player.currentTime(time);
> 					},
> 					doubleTap: true,
> 				},
> 				play: {
> 					handleClick: () => {
> 						if (self.player.paused()) {
> 							self.player.play();
> 						} else {
> 							self.player.pause();
> 						}
> 					},
> 				},
> 				seekRight: {
> 					handleClick: () => {
> 						const time = Number(self.player.currentTime()) + 10;
> 						self.player.currentTime(time);
> 					},
> 					doubleTap: true,
> 				},
> 				lockButton: true
> 			});
> ````
> Somehow it is saying this method is not defined.

How did you import the library, using cdn or npm?
