### ISSUE TITLE
Play/Pause on SpaceBar

### ISSUE THREAD

**Issue by craigjem** [hoangvu12/videojs-overlay-buttons#2]
var vid1 = videojs("vjs-play" + videoInc); 
      vid1.on('dblclick', function() { vid1.requestFullscreen(); }); 
      vid1.on('dblclick', function() { vid1.exitFullscreen(); });
      vid1.on('spacebar', function() { vid1.play(); });
      vid1.on('spacebar', function() { vid1.pause(); });

I am trying to get the video to play/pause on spacebar - ch32
Tried various code examples but cannot get it working, any suggestions would be grealty appreciated

**Comment by craigjem** [comment]
scripts in the header

<script type="text/javascript" src="js/video-js/video.min.js"></script>
<script type="text/javascript" src="js/video-js/videojs-overlay-buttons.min.js"></script>

I am loading video-min.js before your code, so it should pickup on the functions with no issues. It's not returning any JS errors in the console. The above code requestFullscreen and exitFullscreen works no problems, just cannot get the video to pause or play on the spacebar

**Comment by hoangvu12** [comment]
Thank you for your detailed issue. But this is not videojs-overlay-buttons's problem. 

Anyway, this is what I found in StackOverflow

```js
function togglePlayPause() {
  var player = videojs('my_video_1');
  if (player.paused()) {
    player.play();
  } else {
    player.pause();
  }
}

$(function() {
  const videoContainer = document; // replace this with just immediate container of video player
  $(videoContainer).on('keypress', function() {
    const keyCode = event.keyCode || event.which;
    if (keyCode == 32) {
      // targetting all buttons, change with class if you want
      if (event.target.type === 'button') {
        event.target.blur();
        event.preventDefault();
      }
      togglePlayPause();
    }
  });      
});
```

Feel free to open the issue if the problem still there.

Edit: I haven't used videojs for a long time so I don't really sure if I'm wrong.
